language: python
python:
  - "3.8.5"

install:
- sudo apt update
- sudo apt install software-properties-common
- sudo apt-add-repository --yes --update ppa:ansible/ansible
- sudo apt install ansible

script:
  python3 install