version: '3.9'

volumes:
  sharedencryptvolume:
services:
  service_encrypt:
    build: ./encryptjson
    volumes:
      - sharedencryptvolume:/home

  service_decrypt:
    build: ./xmldecrypt
    depends_on:
      - service_encrypt
    ports:
      - '8080:8080'
    volumes:
      - sharedencryptvolume:/home/encryptjson